name: Django CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Load .env file into GitHub environment
      run: |
        # export all key=value pairs into GitHub Actions environment
        while IFS= read -r line; do
          if [[ ! "$line" =~ ^# && -n "$line" ]]; then
            echo "$line" >> $GITHUB_ENV
          fi
        done < .github/workflows/.env

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create test database
      run: |
        PGPASSWORD=postgres psql -h localhost -U postgres -d postgres -c "CREATE DATABASE test_db;"

    - name: Run Migrations
      env:
        POSTGRES_DB: test_db
        POSTGRES_USER: postgres
        DB_PORT: 5432
        DB_HOST: 127.0.0.1
      run: python manage.py migrate

    - name: Run Tests
      run: pytest -v
